# Generated by Django 4.0 on 2023-01-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='image',
        ),
        migrations.AddField(
            model_name='photos',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='photos',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='photos',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
