# Generated by Django 4.0 on 2023-01-17 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_remove_photos_image_photos_image1_photos_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='image1',
            new_name='Display1',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='image2',
            new_name='Display2',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='image3',
            new_name='Display3',
        ),
    ]
