# Generated by Django 4.0 on 2023-01-17 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_rename_image1_photos_display1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='Display1',
            new_name='display1',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='Display2',
            new_name='display2',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='Display3',
            new_name='display3',
        ),
    ]
