# Generated by Django 4.0 on 2023-01-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_sermon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sermon',
            old_name='title',
            new_name='topic',
        ),
        migrations.AddField(
            model_name='sermon',
            name='speaker',
            field=models.CharField(default='Evg Emma Ibrahim', max_length=50),
            preserve_default=False,
        ),
    ]
