# Generated by Django 4.0 on 2023-01-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0007_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=60)),
                ('tel', models.CharField(max_length=12)),
                ('testimony', models.TextField()),
            ],
        ),
    ]
