# Generated by Django 4.0 on 2023-01-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_testimony'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='display1',
            new_name='display',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='display2',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='display3',
        ),
    ]
