# Generated by Django 4.0 on 2023-01-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0010_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='flyer',
            new_name='flier',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
