# Generated by Django 4.0 on 2023-04-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0013_alter_heading_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='flier',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='display',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
