# Generated by Django 4.0 on 2023-04-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0014_alter_event_flier_alter_photos_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='flier',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='heading',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='photos',
            name='display',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
