# Generated by Django 4.1.7 on 2023-04-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0016_alter_heading_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
