# Generated by Django 4.0 on 2023-04-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0017_alter_heading_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defaultpic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
